import CompareTransactions
import DifferentialTransactions
import FetchDisclosures
import ParseDisclosures
import StoreOutput
import os
import time
import json
from datetime import date

# delete all files in a folder at path, excluding gitignore
def clearFolder(path):
    for entry in os.listdir(path):
        if entry != '.gitignore':
            fullpath = os.path.join(path, entry)
            os.remove(fullpath)

# delete all files in all folders containing temporary files generated by program
def clearDataFolders():
    clearFolder('./FinancialDisclosures')
    clearFolder('./GeneratedDiffs')
    clearFolder('./StockAssetsFD')
    clearFolder('./tmp')

# run program on a given representative, outputting a json file containing all discrepancies found
def singleRunDict(representative, token, _refresh):
    FD_IDs = {}
    clearDataFolders()
    FetchDisclosures.main(representative, FD_IDs)
    ParseDisclosures.main()
    DifferentialTransactions.main()
    CompareTransactions.main(representative, token, FD_IDs, _refresh)

# read a json file at path, output as a dictionary
def readJsonFile(path):
    with open(path, 'r') as f:
        return json.load(f)

# run program on all representatives found in json file at path
def LIST_RUN(path, QuiverToken, refresh):
    try:
        representatives = readJsonFile(path)
        for rep in representatives:
            if rep['Completed'] == False:
                print("Running " + rep['BioguideID'])
                singleRunDict(rep, QuiverToken, refresh)
                rep['Completed'] = True
                if refresh:
                    print(rep['BioguideID'] + " Completed, waiting 5 seconds for API throttle")
                    time.sleep(5)
                else:
                    print(rep['BioguideID'] + " Completed")
        print('All representatives have been processed')
        current_date = date.today()
        current_date = current_date.strftime("%Y-%m-%d")
        StoreOutput.main(current_date)
        with open(path, "w") as f:
            json.dump(representatives, f, indent=4)
    except SystemExit as e:
        print(f"Exiting with error: {e}")
        with open(path, "w") as f:
            json.dump(representatives, f, indent=4)

def main():
    try:
        arguments = readJsonFile('./Project_Arguments.json')
    except json.JSONDecodeError:
        print('Input Error: \'./Project_Arguments.json\' could not be decoded')
    LIST_RUN(arguments['RepFilePath'],
             arguments['QuiverAPIToken'],
             arguments['RefreshAPI'])

main()
